#!/usr/bin/env bash
# council_sync.sh — Sync CLAUDE.md into AGENTS.md for Codex, preserving any
# user-owned AGENTS.md.
#
# Usage: council_sync.sh <working_directory>            # write council AGENTS.md
#        council_sync.sh --restore <working_directory>  # undo: restore original or remove
#
# AGENTS.md is Codex/OpenAI's native project-instructions file and may be a
# real, user-owned file. Before writing, any existing AGENTS.md is backed up
# to .council-tmp/AGENTS.md.orig; --restore puts it back (or removes the
# council-written file when no original existed).
set -euo pipefail

RESTORE=false
if [[ "${1:-}" == "--restore" ]]; then
  RESTORE=true
  shift
fi

WORK_DIR="${1:?Usage: council_sync.sh [--restore] <working_directory>}"
WORK_DIR="$(cd "$WORK_DIR" && pwd)"
AGENTS_MD="$WORK_DIR/AGENTS.md"
BACKUP_DIR="$WORK_DIR/.council-tmp"
BACKUP="$BACKUP_DIR/AGENTS.md.orig"
SENTINEL="$BACKUP_DIR/AGENTS.md.council-written"

if [[ "$RESTORE" == "true" ]]; then
  if [[ -f "$BACKUP" ]]; then
    mv "$BACKUP" "$AGENTS_MD"
    rm -f "$SENTINEL"
    echo "Restored original AGENTS.md."
  elif [[ -f "$SENTINEL" ]]; then
    rm -f "$AGENTS_MD" "$SENTINEL"
    echo "Removed council-written AGENTS.md (no original existed)."
  else
    echo "Nothing to restore (no council sync recorded)." >&2
  fi
  exit 0
fi

CLAUDE_MD="$WORK_DIR/CLAUDE.md"
if [[ ! -f "$CLAUDE_MD" ]]; then
  echo "ERROR: No CLAUDE.md found in $WORK_DIR" >&2
  exit 1
fi

mkdir -p "$BACKUP_DIR"
# Council R1: a STALE backup/sentinel from an earlier session must not cause a
# newer user-owned AGENTS.md to be overwritten without a fresh backup. Sync is
# therefore idempotent: restore any previous council state FIRST, then take a
# fresh backup of whatever the user actually has now.
if [[ -f "$BACKUP" ]]; then
  mv "$BACKUP" "$AGENTS_MD"
  rm -f "$SENTINEL"
elif [[ -f "$SENTINEL" ]]; then
  rm -f "$AGENTS_MD" "$SENTINEL"
fi
if [[ -f "$AGENTS_MD" ]]; then
  cp "$AGENTS_MD" "$BACKUP"
  echo "Backed up existing AGENTS.md to $BACKUP"
else
  touch "$SENTINEL"
fi

{
  cat <<'PREAMBLE'
# AGENTS.md — Advisory Context (generated by The Council skill)

You are acting as an external advisory reviewer for this project. The content
below is the project's CLAUDE.md, provided as context. Review what you are
asked to review; do not attempt to modify files.

---

PREAMBLE
  cat "$CLAUDE_MD"
} > "$AGENTS_MD"

echo "AGENTS.md written from CLAUDE.md ($(wc -l < "$AGENTS_MD") lines)."
