#!/usr/bin/env bash
# council_sync.sh — Sync CLAUDE.md into AGENTS.md for Codex, preserving any
# user-owned AGENTS.md.
#
# Usage: council_sync.sh <working_directory>            # write council AGENTS.md
#        council_sync.sh --restore <working_directory>  # undo: restore original or remove
#
# AGENTS.md is Codex/OpenAI's native project-instructions file and may be a
# real, user-owned file. Before writing, any existing AGENTS.md is backed up
# to .council-tmp/AGENTS.md.orig; --restore puts it back (or removes the
# council-written file when no original existed).
set -euo pipefail

RESTORE=false
if [[ "${1:-}" == "--restore" ]]; then
  RESTORE=true
  shift
fi

WORK_DIR="${1:?Usage: council_sync.sh [--restore] <working_directory>}"
WORK_DIR="$(cd "$WORK_DIR" && pwd)"
AGENTS_MD="$WORK_DIR/AGENTS.md"
BACKUP_DIR="$WORK_DIR/.council-tmp"
BACKUP="$BACKUP_DIR/AGENTS.md.orig"
SENTINEL="$BACKUP_DIR/AGENTS.md.council-written"

# Sentinel-staleness guard (final review): a SENTINEL is only trustworthy if the
# AGENTS.md it points at is actually council-generated. If a session died before
# --restore and the user has since authored their own AGENTS.md, the stale
# sentinel would otherwise cause that user file to be deleted. This preamble
# match covers BOTH the v1.4.0 header ("generated by The Council skill") AND the
# legacy 1.3.0 generation ("Advisory Context (synced from CLAUDE.md)").
council_written() {
  [[ -f "$1" ]] && grep -q 'generated by The Council skill\|Advisory Context (synced from CLAUDE.md)' "$1"
}

if [[ "$RESTORE" == "true" ]]; then
  if [[ -f "$BACKUP" ]]; then
    mv "$BACKUP" "$AGENTS_MD"
    rm -f "$SENTINEL"
    echo "Restored original AGENTS.md."
  elif [[ -f "$SENTINEL" ]]; then
    if [[ -f "$AGENTS_MD" ]] && ! council_written "$AGENTS_MD"; then
      # Stale sentinel, but the file on disk is NOT council-written — the user
      # authored their own AGENTS.md after a session died pre-restore. Never
      # delete user content: leave the file, drop the stale sentinel.
      rm -f "$SENTINEL"
      echo "WARNING: AGENTS.md is user-authored (not council-written); left in place. Removed stale sentinel." >&2
    else
      rm -f "$AGENTS_MD" "$SENTINEL"
      echo "Removed council-written AGENTS.md (no original existed)."
    fi
  else
    echo "Nothing to restore (no council sync recorded)." >&2
  fi
  exit 0
fi

CLAUDE_MD="$WORK_DIR/CLAUDE.md"
if [[ ! -f "$CLAUDE_MD" ]]; then
  echo "ERROR: No CLAUDE.md found in $WORK_DIR" >&2
  exit 1
fi

mkdir -p "$BACKUP_DIR"
# Council R1: a STALE backup/sentinel from an earlier session must not cause a
# newer user-owned AGENTS.md to be overwritten without a fresh backup. Sync is
# therefore idempotent: restore any previous council state FIRST, then take a
# fresh backup of whatever the user actually has now.
if [[ -f "$BACKUP" ]]; then
  mv "$BACKUP" "$AGENTS_MD"
  rm -f "$SENTINEL"
elif [[ -f "$SENTINEL" ]]; then
  if [[ -f "$AGENTS_MD" ]] && ! council_written "$AGENTS_MD"; then
    # Stale sentinel from a dead session, but the user has authored their own
    # AGENTS.md since. Treat it as user-owned: back it up (so --restore can hand
    # it back) instead of deleting, and drop the stale sentinel. The block below
    # will then take a fresh backup and overwrite with council content.
    cp "$AGENTS_MD" "$BACKUP"
    rm -f "$SENTINEL"
    echo "Preserved user-authored AGENTS.md (stale sentinel); backed up to $BACKUP" >&2
  else
    rm -f "$AGENTS_MD" "$SENTINEL"
  fi
fi
if [[ -f "$AGENTS_MD" ]]; then
  cp "$AGENTS_MD" "$BACKUP"
  echo "Backed up existing AGENTS.md to $BACKUP"
else
  touch "$SENTINEL"
fi

{
  cat <<'PREAMBLE'
# AGENTS.md — Advisory Context (generated by The Council skill)

You are acting as an external advisory reviewer for this project. The content
below is the project's CLAUDE.md, provided as context. Review what you are
asked to review; do not attempt to modify files.

---

PREAMBLE
  cat "$CLAUDE_MD"
} > "$AGENTS_MD"

echo "AGENTS.md written from CLAUDE.md ($(wc -l < "$AGENTS_MD") lines)."
