#!/usr/bin/env bash
# Council must never take ownership of a project's AGENTS.md.
#   S1. Existing AGENTS.md remains byte-identical; no backup is created.
#   S2. Missing AGENTS.md remains missing.
#   S3. Repeated sync calls remain read-only.
#   S4. --restore still recovers state left by an interrupted pre-1.6.2 run.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SYNC="$REPO_ROOT/skills/the-council/scripts/council_sync.sh"
TMPDIR_TEST="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_TEST"' EXIT
pass() { echo "PASS: $1"; }
fail() { echo "FAIL: $1"; exit 1; }

P="$TMPDIR_TEST/proj"; mkdir -p "$P"
echo "# My CLAUDE rules" > "$P/CLAUDE.md"

# S1
echo "# USER OWNED AGENTS FILE" > "$P/AGENTS.md"
BEFORE="$(shasum -a 256 "$P/AGENTS.md")"
bash "$SYNC" "$P"
[[ "$(shasum -a 256 "$P/AGENTS.md")" == "$BEFORE" ]] || fail "S1: AGENTS.md changed"
[[ ! -e "$P/.council-tmp/AGENTS.md.orig" ]] || fail "S1: unnecessary backup created"
pass "S1: existing AGENTS.md remains byte-identical"

# S2
rm -f "$P/AGENTS.md"; rm -rf "$P/.council-tmp"
bash "$SYNC" "$P"
[[ ! -e "$P/AGENTS.md" ]] || fail "S2: Council created AGENTS.md"
pass "S2: missing AGENTS.md remains missing"

# S3 — repeated sync is a read-only no-op.
rm -f "$P/AGENTS.md"; rm -rf "$P/.council-tmp"
echo "# USER OWNED AGENTS FILE" > "$P/AGENTS.md"
BEFORE="$(shasum -a 256 "$P/AGENTS.md")"
bash "$SYNC" "$P" >/dev/null
bash "$SYNC" "$P" >/dev/null
[[ "$(shasum -a 256 "$P/AGENTS.md")" == "$BEFORE" ]] || fail "S3: repeated sync changed AGENTS.md"
pass "S3: repeated sync is read-only"

# S4 — preserve recovery for a backup left by an older interrupted run.
rm -f "$P/AGENTS.md"; rm -rf "$P/.council-tmp"; mkdir -p "$P/.council-tmp"
echo "# ORIGINAL PROJECT AGENTS" > "$P/.council-tmp/AGENTS.md.orig"
touch "$P/.council-tmp/AGENTS.md.council-written"
echo "# AGENTS.md — Advisory Context (generated by The Council skill)" > "$P/AGENTS.md"
bash "$SYNC" --restore "$P" >/dev/null
grep -q "ORIGINAL PROJECT AGENTS" "$P/AGENTS.md" || fail "S4: legacy backup was not restored"
pass "S4: legacy interrupted-run backup remains recoverable"

echo ""
echo "ALL SYNC TESTS PASSED"
